### PR TITLE
Fix banner definitions for several route networks [BUGFIX]

### LINKED ISSUE #1160: Several bannered shields showing up with wrong icon and/or color
Many bannered shields are showing up with the wrong icon or color. This appears to have been caused by #1073.

Examples include bannered Interstate routes:

[image](https://americanamap.org/#map=7.53/41.96/-76.736/0/1)

_Originally posted by @jleedev in https://github.com/osm-americana/openstreetmap-americana/issues/1158#issuecomment-2358205506_

Business Farm-to-Market Roads in Texas are also affected:

[image](https://americanamap.org/#map=14.54/30.00088/-95.26844)

### PR DESCRIPTION
**Pull request by ZeLonewolf**
Fixes #1160 

This PR fixes the definitions of several route networks which copied from a parent route network.  Since the parent route network had banners defined, the child network inappropriately inherited those banners.  This fixes the issue for these routes by separating out the style components of reusable networks into separate constants.

### CODE REVIEW

File: src/js/shield_defs.js [hunk 1]
```diff
@@ -2751,10 +2765,7 @@ export function loadShields() {
       "US:TX:Loop:Express:Toll": ["EXPR", "LOOP"],
     },
   };
-  shields["US:TX:Toll"] = shields["US:TX:NTTA"] = roundedRectShield(
```
Comment (1ec5) [inline src/js/shield_defs.js:2754]: This eliminates support for `US:TX:NTTA`.

Comment (ZeLonewolf) [reply src/js/shield_defs.js:2754]: It's present in the `US:TX:Toll` block, this was a duplicate.  Is it not showing in the map?

Comment (ZeLonewolf) [reply src/js/shield_defs.js:2754]: Yep, seems to be working here:
https://preview.ourmap.us/pr/1173/#map=12/32.7113/-97.36525

**Review by claysmalley — APPROVED** [review]
